apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/shared/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromium-selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromium-selenium
  template:
    metadata:
      labels:
        app: chromium-selenium
    spec:
      containers:
        - name: chromium
          image: your-chromium-image:latest
          volumeMounts:
            - name: shared-data
              mountPath: /path/to/shared/data
        - name: selenium
          image: your-selenium-image:latest
          volumeMounts:
            - name: shared-data
              mountPath: /path/to/shared/data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc
